### ISSUE TITLE
[BUG] 급식 필요 없는 문자 삭제 원할하지 않음

### ISSUE THREAD

**Issue by koi312500** [chanhyokpark/dshs-app#22]
**오류 설명**
기존에, 나이스에서 표시해주는 알레르기등의 여러 표시를 없애주셨던것으로 기억하는데 현재 급식에는 지속적으로 (석) 과 같은 표시가 나오는 것을 볼 수 있습니다. 다음과 같은 기호들을 없애주세요.

**재현 방법**
4월 3일자 급식을 확인해 주세요.

**예상한 행동**
음식 메뉴만 뜨는 창

**스크린샷**
![image](https://github.com/chanhyokpark/dshs-app/assets/30021124/1d2429fe-1d97-4bc0-a861-1d1fd3cbeb85)

**사용한 환경:**
 - 사용한 환경과 관련 없는 버그입니다. 다만, 첨부해봅니다.
 - OS: Windows 11 Insider Preview, Android 14
 - 브라우저: Firefox / Edge

**기타**
(석) 과 같은 것은 괄호 열기 닫기로 가릴 수 있을것이라 생각하며, 뒤에 달린 특수 문자 세트를 삭제할 수 있지 않을까 생각합니다.

**Comment by chanhyokpark** [comment]
레겍스 수정하기 귀찮아요 나중에 할거임

**Comment by chanhyokpark** [comment]
수정했습니다. 다음 업데이트부터 적용됩니다
