### ISSUE TITLE
[BUG] 이름이 다르게 표시됨.

### ISSUE THREAD

**Issue by koi312500** [chanhyokpark/dshs-app#23]
**오류 설명**
신청 화면에 신청을 하면 "@@@" 라고 표시되며, 이 상태에서 새로 고침시 "@@@3"라 표시되고, 이는 다시 신청시 "@@@" 로 변화합니다.

**재현 방법**
오류 설명에 자세하게 서술해 두었습니다.

**예상한 행동**
항상 @@@3 내지는 @@@로 표시되기를 원했습니다.
또, F5 진행시 제 좌석이 파란색으로 뜨기를 원했으나, 그러하지 않았습니다.

**스크린샷**

**사용한 환경:**
 - OS: Windows 11
 - 브라우저: Firefox

**기타**
Plz do not abort this issue.

**Comment by chanhyokpark** [comment]
해결함, 다음 커밋 때 수정될 예정

**Comment by chanhyokpark** [comment]
스크린샷에 타 학생 개인정보가 포함되어 있어 삭제합니다
