### ISSUE TITLE
[iOS/macOS] 급식 메뉴 누르면 검색되는 기능

### ISSUE THREAD

**Issue by chanhyokpark** [chanhyokpark/dshs-app#46]
**요청자**: 658817887f3b6d602fbf5195
건의합니다
메뉴가 뭔지 몰라서 구글에 검색할때가 많아요

**기기 정보**
앱 버전: 1.1.4
OS: iOS
OS 버전: 18.0
모델: iPad Air (5th generation)

**Comment by chanhyokpark** [comment]
구현 중

**Comment by chanhyokpark** [comment]
구현되었습니다. 다음 빌드부터 적용됩니다

**Comment by koi312500** [comment]
기능이 사라졌어요 다시 추가해주세요
